[build]
function = "functions/"
publish = ""
command = "sed -i \"s|SHORTIO_API_TOKEN_PUBLIC|${SHORTIO_API_TOKEN_PUBLIC}|g\" netlify.toml && yarn build"

[[redirects]]
from = "/api/shortIO"
to = "https://api.short.io/links/public"
status = 200

[[redirects]]
from = "/api/shortIOlinks"
to = "/.netlify/functions/shortIOlinks"
status = 200

[[headers]]
for = "/api/shortIO"
[headers.values]
accept = "application/json"
Content-Type = "application/json"
authorization = "SHORTIO_API_TOKEN_PUBLIC"

[dev]
functionsPort = 3000
