[build]
    function = "functions/"
    publish = ""

[[redirects]]
from = "/api/shortIO"
to = "https://api.short.io/links/public"
status = 200

[[redirects]]
from = "/api/shortIOlinks"
to = "/.netlify/functions/shortIOlinks"
status = 200

[[headers]]
for = "/api/shortIO"
    [headers.values]
    accept = "application/json"
    Content-Type = "application/json"

[dev]
    functionsPort=3000
