[[redirects]]
from = "/api/shortIO"
to = "https://api.short.io/links/public"
status = 200

[[headers]]
for = "/api/shortIO"
    [headers.values]
    accept = "application/json"
    Content-Type = "application/json"
    authorization = "pk_Fyb6rXgT61WeumwC"
